version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Instalando dependencias...
      - npm install
  build:
    commands:
      - echo Compilando la aplicación...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: build
