version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: elearning_postgres
    environment:
      POSTGRES_DB: elearning_narino
      POSTGRES_USER: elearning_user
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - elearning_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: elearning_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@elearning.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - elearning_network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  elearning_network:
    driver: bridge 